[package]
name = "astrotools"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/devDucks/astrotools/"
readme = "README.md"
description = "Basic building block for the lightspeed protocol and lightspeed compliant drivers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.1"
lightspeed-astro = { version = "0.6.1", git = "https://github.com/devducks/lightspeed", rev = "v0.6.1" }

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",
]