[package]
name = "astrotools"
version = "0.3.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/devDucks/astrotools/"
readme = "README.md"
description = "Basic building block for the lightspeed protocol and lightspeed compliant drivers"

[dependencies]
serialport = "4.1"
lightspeed-astro = "0.6"

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",
]
