[package]
name = "astrotools"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.1"
lightspeed = { git = "https://github.com/devducks/lightspeed", rev = "v0.6.1" }

[dependencies.uuid]
version = "1.0.0"
features = [
    "v4",
    "fast-rng",
]